language: go
sudo: required
language: go
go:
  - "1.13.x"
  - "1.14.x"
  - tip

matrix:
  fast_finish: true

env: GO111MODULE=on

git:
  depth: 10

go_import_path: github.com/semihalev/sdns

script: 
  - make test
 
after_success:
  - bash <(curl -s https://codecov.io/bash)
